name: test

on:
  push:
    branches:
      - "v2"
    paths:
      - ".github/workflows/test.yml"
      - "assets/**"
      - "tests/**"
  pull_request:
    branches:
      - "v2"
    paths:
      - ".github/workflows/test.yml"
      - "assets/**"
      - "tests/**"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  maa-tools-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: Setup pnpm
        uses: pnpm/action-setup@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run maa-tools test
        run: pnpm test

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: logs
          path: tests/maatools

  map-tracker-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: pip install -r ./tools/map_tracker/requirements.txt

      - name: Run MapTracker test
        run: python ./tools/map_tracker/map_tracker_tester.py batch_test -i ./tests/MaaEndTestset/Win32/Official_CN/map_tracker
